oc_home:
    path: ../
    defaults: {_controler: OCCoreBundle:index}


oc_platform_home:
    path: /{page}
    defaults: {_controller: OCPlatformBundle:Advert:index, page: 1}
    requirements:
        page: \d*

oc_platform_view:
    path: /advert/{id}
    defaults: {_controller: OCPlatformBundle:Advert:view}
    requirements:
        page: \d+

oc_platform_add:
    path: /add
    defaults: {_controller: OCPlatformBundle:Advert:add}


oc_platform_edit:
    path: /edit/{id}
    defaults: {_controller: OCPlatformBundle:Advert:edit}
    requirements:
        page: \d+

oc_platform_delete:
    path: /delete/{id}
    defaults: {_controller: OCPlatformBundle:Advert:delete}
    requirements:
        page: \d+